apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: cabinet-deployment
  labels:
    name: cabinet-deployment-name
    app: cabinet-deployment-app
    version: 1.0.0
spec:
 replicas: 2
 strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
 selector:
  matchLabels:
    app: cabinet-app
 template:
  metadata:
    name: cabinet-pod
    labels:
     name: cabinet
     app: cabinet-app
     version: 1.0.0
  spec:
   containers:
    - name: cabinet-container
      image: cabinet:latest
      imagePullPolicy: IfNotPresent
      ports:
       - containerPort: 8989
---
apiVersion: v1
kind: Service
metadata:
 namespace: default
 name: cabinet-service
spec:
 type: ClusterIP
 selector:
  app: cabinet-app
 ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8989
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 namespace: default
 name: cabinet-ingress
spec:
 ingressClassName: nginx
 rules:    
  - host: "www.cabinet.com"
    http:
     paths:
       - path: /files-search
         pathType: Exact
         backend:
           service:
             name: cabinet-service
             port:
              number: 80
              
       - path: /file-insert
         pathType: Exact
         backend:
          service:
            name: cabinet-service
            port:
             number: 80

       - path: /folder-files-get
         pathType: Exact
         backend:
          service:
            name: cabinet-service
            port:
             number: 80
       
       - path: /folders-get
         pathType: Exact
         backend:
           service:
             name: cabinet-service
             port:
              number: 80
 
