apiVersion: apps/v1
kind: Deployment
metadata:
  name: cabinet-mock
  labels:
    app.kubernetes.io/name: cabinet-mock
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 1
  selector:
    matchLabels:
      app: cabinet-mock
  template:
   metadata:
    labels:
      app: cabinet-mock
   spec:
     containers:
      - name: cabinet-mock
        image: mock-app:latest
        imagePullPolicy: Never
        ports:
         - containerPort: 8989

---
apiVersion: v1
kind: Service
metadata:
  name: cabinet-mock-service
  labels:
    app: cabinet-moxk
    version: v1
spec:
 type: LoadBalancer
 selector:
   app.kubernetes.io/name: cabinet-mock
 ports:
  - protocol: TCP
    port: 8989
    targetPort: 8989
 
