apiVersion: v1
kind: Pod
metadata:
 name: cabinet-pod
 labels:
   app: cabinet-app
   version: 1.0.1
spec:
 containers:
  - name: cabinet-container
    image: cabinet:latest
    imagePullPolicy: Never
    ports:
     - containerPort: 8989
---
apiVersion: v1
kind: Service
metadata:
  name: cabinet-svc
spec:
 type: NodePort
 selector:
   app: cabinet-app
 ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8989

