apiVersion: v1
kind: Namespace
metadata:
  name: nginx-namespace
  labels:
    app: nginx-namespace
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx-namespace
  labels:
    app: nginx
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
   matchLabels:
       app: nginx
  template:
    metadata:
      labels:
        app: nginx
        version: v1
    spec:
     containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
         - containerPort: 80
