apiVersion: v1
kind: Service
metadata:
 name: upstream-srv
 namespace: ckad
spec:
 type: NodePort
 selector:
   app.kubernets.io/name: upstream-app
 ports:
  - name: upstrea-port
    protocol: TCP
    port: 8080
    targetPort: 8080
