apiVersion: v1
kind: Service
metadata:
 name: upstream-srv
 namespace: ckad
spec:
 type: LoadBalancer
 selector:
   app: upstream-app
 ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    #externalIPs:
    #- 198.51.100.32
