apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-result
  namespace: voting-app-namespace
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
        name: voting-result-pod
        app: voting-app
  template:
    metadata:
      labels:
        name: voting-result-pod
        app: voting-app
    spec:
      containers:
       - name: voting-result-container
         image: kodekloud/examplevotingapp_result:v1
         imagePullPolicy: IfNotPresent
         ports:
           - containerPort: 80

