apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-front-app
  namespace: voting-app-namespace
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      name: voting-front-pod
      app: voting-app
  template:
   metadata:
      name: voting-front-pod
      labels:
         name: voting-front-pod
         app: voting-app
   spec:
     containers:
        - name: voting-app-container
          image: kodekloud/examplevotingapp_vote:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80



