apiVersion: v1
kind: Service
metadata:
  name: voting-app-svc
  namespace: voting-app-namespace
spec:
 type: LoadBalancer
 selector:
   name: voting-front-pod
   app: voting-app
 ports:
  - name: voting-front
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30004

