apiVersion: apps/v1
kind: Deployment
metadata:
  name: upstream-dply
  namespace: ckad
spec:
  replicas: 2
  selector:
    matchLabels:
      app: upstream-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
     metadata:
       name: upstream
       labels:
         app: upstream-app
         version: 1.0.0
     spec:
       containers:
         - name: upstream-conrt
           image: upstream
           imagePullPolicy: IfNotPresent
           ports:
             - containerPort: 8080
           resources:
             requests:
               memory: 2Gi
               cpu: 100m
             limits:
               memory: 2Gi
               cpu: 100m

    
