apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  namespace: voting-app-namespace
  labels:
    app: voting-app
    name: database-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      name: voting-database-pod
      app: voting-app
  template:
    metadata:
      labels:
        name: voting-database-pod
        app: voting-app
    spec:
     containers:
       - name: voting-database-container
         image: postgres
         imagePullPolicy: IfNotPresent
         ports:
           - containerPort: 5432
         env:
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
