apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  selector:
    name: voting-database-pod
    app: voting-app
  ports:
    - name: voting-db
      protocol: TCP
      port: 5432
      targetPort: 5432
