apiVersion: apps/v1
kind: Deployment
metadata:
  name: in-memory-db-deployment
  labels:
     name: in-memory-db-deployment
     app: voting-app
spec:
 replicas: 1
 strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 1
 selector:
  matchLabels:
    name: in-memory-db-pod
    app: voting-app
 template:
   metadata:
     labels:
        name: in-memory-db-pod
        app: voting-app
   spec:
    containers:
     - name: in-memory-db-container
       image: redis
       imagePullPolicy: IfNotPresent
       ports:
        - containerPort: 6379
       
