apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-worker-deployment
  namespace: voting-app-namespace
  labels:
    name: worker-app-pod
    app: voting-app
spec:
 replicas: 1
 strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 1
 selector:
   matchLabels:
     name: worker-app-pod
     app: voting-app
 template:
   metadata:
     labels:
       name: worker-app-pod
       app: voting-app
   spec:
    containers:
     - name: voting-worker-container
       image: kodekloud/examplevotingapp_worker:v2
       imagePullPolicy: IfNotPresent

         
