apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ckad
  name: upstream-dply
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
        app: upstream-app
  template:
    metadata:
       name: upstream
       labels:
         app: upstream-app
         version: 1.0.0
    spec:
      containers:
        - name: upstream-contr
          image: upstream
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
               cpu: 100m
               memory: 2Gi
            requests:
               cpu: 100m
               memory: 1Gi
          env:
           - name: SPRING_PROFILES_ACTIVE
             valueFrom:
               configMapKeyRef:
                   name: upstream-cm
                   key: active 
